DEFINE input:inference "rdfs_entailments"

PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct:<http://purl.org/dc/terms/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?c ?l ?a ?d FROM <##graphURI##>
WHERE {
  {
    ?c rdfs:label ?l.
    ?c skos:broader <##scheme##>.

    OPTIONAL {
      ?c skos:narrower ?n.
      ?n skos:inScheme ?d.
    }

    OPTIONAL {
      ?c skos:prefLabel ?a.
      FILTER ( LANG(?a) = "##clientLanguage##" )
    }
    FILTER ( LANG(?l) = "en")
  }
  UNION
  {
    ?c rdfs:label ?l.
    <##scheme##> skos:member ?c.

    OPTIONAL {
     {
        ?c skos:narrower ?n.
        ?n skos:inScheme ?d.
      } UNION {
        ?c skos:member ?n.
        ?n skos:inScheme ?d.
      }
    }

    OPTIONAL {
      ?c skos:broader ?e.
      <##scheme##> skos:member ?e.
    }

    OPTIONAL {
      ?c rdfs:label ?a.
      FILTER ( LANG(?a) = "##clientLanguage##" )
    }
    FILTER ( LANG(?l) = "en" && !BOUND(?e))
  }
}
ORDER BY ASC(?a) ASC(?l)



