DEFINE input:inference "rdfs_entailments"

PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct:<http://purl.org/dc/terms/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?c ?l ?a ?d 
FROM <##graphURI##>
FROM <##graphURI2##>
WHERE {
  ?c rdfs:label ?l.
  ?c skos:inScheme <##scheme##>.
  OPTIONAL {
    ?c skos:broader ?b.
  }

  OPTIONAL {
    ?f skos:member ?c.
  }

  OPTIONAL {
    {
      ?c skos:narrower ?n.
      ?n skos:inScheme ?d.
    } UNION {
      ?c skos:member ?n.
      ?n skos:inScheme ?d.
    }
  }

  OPTIONAL {
    ?c rdfs:label ?a.
    FILTER ( LANG(?a) = "##clientLanguage##" )
  }

  FILTER ( LANG(?l) = "en" && !BOUND(?b) && !BOUND(?f) )
}
ORDER BY ASC(?a) ASC(?l)
